# This workflow verifies project files are formatted according to Black and isort
# https://black.readthedocs.io/en/stable/integrations/github_actions.html
# https://pycqa.github.io/isort/docs/configuration/github_action.html

name: Lint
on: pull_request
permissions:
  contents: read
jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Check formatting with Black
      uses: psf/black@stable
      with:
          options: "--check --verbose"
          version: "~= 23.0"
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Check imports with isort
      uses: isort/isort-action@v1
      with:
        requirements-files: "requirements.txt"