name: Build, push and deploy

on:
  workflow_dispatch:
jobs:
  build-push-deploy:
    name: Build, push and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build . --tag ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy DigitalOcean App
        uses: digitalocean/app_action/deploy@v2
        with:
          app_name: otto
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}